templates:
  - "regmonkey_scatter"
  - "regmonkey_line"
  - "regmonkey_twoline"

color_style:
  qualitative_scatter_color:
    - "#4477AA"
    - "#EE6677"
    - "#228833"
    - "#CCBB44"
    - "#66CCEE"
    - "#AA3377"
    - "#BBBBBB"
  qualitative_line_color:
    - "#4477AA"
    - "#66CCEE"
    - "#CCBB44"
    - "#AA3377"
    - "#228833"
    - "#EE6677"
    - "#BBBBBB"
  discrete_color_sequence:
    - "#141F52"
    - "#1F2E7A"
    - "#2E45B8"
    - "#475ED1"
    - "#D6DBF5"
    - "#EBEDFA"
  two_line_color:
    - "#00004d"
    - "#757C88"
    - "#757C88"
  background_color: "#EFF5F5"
  text_color: "#3F5661"
  legend_background_color: "rgba(255, 255, 255, 0)" #0 represents the alpha (opacity) component, making the color fully transparent
  grid_color: "#BBBBBB"
  zeroline_color: "#B7C6CF"

font_style:
  default_font: "MPLUS1p"
  available_list:
    - "MPLUS1p"
    - "UDEVGothic"

common:
  title_fontsize: 16
  xlabel_fontsize: 12
  ylabel_fontsize: 12
  legend_fontsize: 10
  tick_fontsize: 10
  text_fontsize: 10
  margin:
    plotly: { "l": 80, "r": 40, "t": 60, "b": 40 }

scatter:
  opacity: 0.7
  gridline:
    gridwidth: 0.1
    griddash: "dot"
  markersize:
    matplotlib: 3

line:
  opacity: 0.9
  gridline:
    gridwidth: 0.1
    griddash: "dot"
